#+ endpoint: https://fuseki.dev.odissei.nl/skosmos/sparql
#+ defaults:
#+   - label: OMZETPS213110113


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?iri ?lbl

 WHERE {
  GRAPH <https://cbs.nl/variables/>
  {?iri skos:altLabel ?lbl .
    
    FILTER sameTerm(lcase(?lbl),lcase(?_label_nl)) 
    FILTER langMatches( lang(?lbl), "NL" ) 
   
  }
} LIMIT 3
