#+ endpoint: http://portal.odissei.nl:7200/repositories/ODISSEI-DEMO

PREFIX dct:  <http://purl.org/dc/terms/> 
PREFIX ns1_CBSdcatDuplicate: <https://data.overheid.nl/dcat.rdf#>

select DISTINCT ?datasetIRI ?datasetPublisher
where {
    ?datasetIRI dct:spatial ?_location_iri .
    {?datasetIRI dct:publisher ?datasetPublisher}
    UNION
    {?datasetIRI ns1_CBSdcatDuplicate:publisher ?datasetPublisher
}