#+ endpoint: http://portal.odissei.nl:7200/repositories/margheritatest
#+ defaults:
#+   - dataset: http://www.cbs-data.com/0b01e410800a0eb5

PREFIX cbs: <http://www.cbs-data.com/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT 
?keyword
(group_concat(DISTINCT ?elsstConcept;separator="'\n\n'") as ?elsstConcepts)
(group_concat(DISTINCT ?elsstLabel;separator="'\n\n'") as ?elsstLabels)
WHERE {
    ?_dataset_iri  cbs:keyword ?keyword ;
             dct:subject ?elsstConcept .
    ?elsstConcept skos:prefLabel ?elsstLabel 
} GROUP BY ?keyword
